### ISSUE TITLE
this cause intellisense for html problem

### ISSUE THREAD

**Issue by kinanson** [onixie/angular-component-extension#1]
I like this can help inline html format but also cause language service not work for html object property intellisense.can you try it and fix that?

**Comment by onixie** [comment]
Could you provide more detail about your problem? I'll fix it ASAP.

The extension is really very young and fragile, and only used by a small team.
I would be grateful for any suggestions.  Thanks.

**Comment by kinanson** [comment]
yes.I will provide you some photo and detail.I had install https://github.com/angular/vscode-ng-language-service.
I can get class of property intellisense please see below photo
![image](https://cloud.githubusercontent.com/assets/5998113/25209556/7e3cea3e-25ae-11e7-8887-9689195dd7a7.png)

If I install this extension and i can't get intellisense please see below
![1](https://cloud.githubusercontent.com/assets/5998113/25209620/e3dc94ac-25ae-11e7-8398-55226e324190.gif)

I also hope get intellisense for  inline style If you can.thanks
