### ISSUE TITLE
Pipe support 

### ISSUE THREAD

**Issue by vovikdrg** [onixie/angular-component-extension#2]
Would be nice to have pipe support :)

**Comment by onixie** [comment]
@vovikdrg 

I'm sorry for the late reply.  I will consider to add pipe support. 
But to make some time is a little hard recently. I will work on this later. 

BTW, do you think module aware features are necessary? such as goto declared module, etc.

**Comment by vovikdrg** [comment]
@onixie Why you mean its hard to implement? (I haven't check sources so just curious ) Its kinda the same thing as component but you load all what has attribute pipe and autocomplete should kick in after you tipe "|" instead of "<" as for components

But module aware you mean inside of pipe that you can structure? if yes then i dont care usually i know which pipe i want the problem is spelling Plus ctrl+click to go pipe file..
