### ISSUE TITLE
Not work with GraphQL for VSCode extension

### ISSUE THREAD

**Issue by sandangel** [onixie/angular-component-extension#3]
This extension is great but unfortunately it will disable GraphQL for VSCode extension syntax highlighting for embedded `gql` tag while angular2-inline work pretty well. But angular2-inline does not have code formatting. Can you review GraphQL for VSCode and resolve conflict part?

with angular-component-extension
![image](https://user-images.githubusercontent.com/22189661/34020987-b6bafbd4-e17a-11e7-907b-3ce6b7ea988f.png)

without angular-component-extension
![image](https://user-images.githubusercontent.com/22189661/34021025-d3230014-e17a-11e7-99ab-6d42f19515b7.png)

**Comment by onixie** [comment]
let it be the homework of mine this weekend.
