### ISSUE TITLE
IntelliSense in HTML is not working

### ISSUE THREAD

**Issue by deftomat** [onixie/angular-component-extension#5]
It crashed the whole IntelliSense when you tried to use it in HTML.

IntelliSense for our custom components in HTML will never resolve. As a consequence, the whole IntelliSense in the whole project will stop working (event in TypeScript files).

See:
![aug-30-2018 15-59-30](https://user-images.githubusercontent.com/5549148/44856529-f369a580-ac6d-11e8-98b0-19ecc0efa7c0.gif)

However, it will work after a VSCode restart:
![aug-30-2018 16-00-54](https://user-images.githubusercontent.com/5549148/44856576-14ca9180-ac6e-11e8-9eb5-e4e158bd0899.gif)

**So, it fails only when you add a NEW element.**

I tried to disable all other extensions and still nothing.

The funny thing is that I had no issue with it last week. I even tried to downgrade a VSCode to 1.25. and still the same issue. So, maybe I've add some component which causing this issue as other extensions and also a VSCode version had no effect on it.

**Comment by deftomat** [comment]
UPDATE: 
I discovered that the issue is caused by doc comments...

This is causing the issue:
```
export class HeadingComponent {
  /** Overrides a heading level */
  @Input() level?: number;
}
```

This is fine:
```
export class HeadingComponent {
  // Overrides a heading level
  @Input() level?: number;
}
```

**Comment by onixie** [comment]
@deftomat 

Sorry for the late response.
I will try to fix it within next week.

**Comment by deftomat** [comment]
@onixie Awesome, thanks

**Comment by onixie** [comment]
There is a cyclic reference in jsdoc structure parsed by typescript language service, which causes the problem. It should be not so difficult to solve.
